/**
 * HadeethEnc English Translation Dataset (v1.25.0)
 *
 * Sourced directly from official HadeethEnc.com_en-v1.25.0.xlsx workbook.
 * Auto-generated by scripts/import-hadeethenc-m9h.mjs.
 *
 * DO NOT EDIT DIRECTLY.
 */

export const HADEETHENC_DATASET_MANIFEST = Object.freeze({
  "provider": "hadeethenc",
  "language": "en",
  "datasetVersion": "v1.25.0",
  "lastUpdated": "2026-05-10 17:43:35",
  "sourceUrl": "https://hadeethenc.com/en",
  "updateCheckUrl": "https://hadeethenc.com/en/check/en/v1.25.0",
  "sourceFileName": "HadeethEnc.com_en-v1.25.0.xlsx",
  "rightsPolicy": "approved-redistribution",
  "attribution": "HadeethEnc.com",
  "contentScope": "translated-hadith-text",
  "workbookChecksum": "339d148eb7425b7f2d48dd7521a969e4aa4a35b5d35a7c4a1c1b67043b5ee218",
  "recordCount": 17
});

export const HADEETHENC_ENGLISH_TRANSLATIONS = Object.freeze({
  "2758": {
    "id": "2758",
    "title": "Whoever performs Hajj without engaging in rafath  (sexual relations or obscene speech) or sinning will return like the day his mother gave birth to him",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported: I heard the Messenger of Allah (may Allah’s peace and blessings be upon him) say: \"Whoever performs Hajj without engaging in rafath  (sexual relations or obscene speech) or sinning will return like the day his mother gave birth to him.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/2758",
    "sha256": "e3ea18090673d180b8b547df88e76d78f2522a6889cd980fa1a8bd9028a669ea",
    "charCount": 291
  },
  "3272": {
    "id": "3272",
    "title": "By the One in Whose Hand Muhammad's soul is, there is nobody of this Ummah (community), whether they be Jewish or Christian, who hears of me and then dies without believing in what I was sent with except that he will be among the people of Hellfire",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported that the Messenger of Allah (may Allah's peace and blessings be upon him) said: \"By the One in Whose Hand Muhammad's soul is, there is nobody of this Ummah (community), whether they be Jewish or Christian, who hears of me and then dies without believing in what I was sent with except that he will be among the people of Hellfire.\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/3272",
    "sha256": "901c9d829629724d7a73805fad966faa5a2dba4c066e5e4c1164d19288de2e6e",
    "charCount": 385
  },
  "3686": {
    "id": "3686",
    "title": "Convey from me even if one verse, and narrate from the Children of Israel, and there is no sin in doing that. And whoever intentionally tells a lie about me, let him occupy his seat in Hellfire",
    "hadith_text": "‘Abdullāh ibn ‘Amr (may Allah be pleased with him) reported: The Prophet (may Allah's peace and blessings be upon him) said: \"Convey from me even if one verse, and narrate from the Children of Israel, and there is no sin in doing that. And whoever intentionally tells a lie about me, let him occupy his seat in Hellfire.\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Al-Bukhāri]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/3686",
    "sha256": "17e90e7a8fb962ecb80c1c2a67ceefc72f292db750feee491cbeb7ba8c5ba1de",
    "charCount": 321
  },
  "3689": {
    "id": "3689",
    "title": "Direct me to a deed that will make me enter Paradise if I do it. He said: \"Worship Allah and do not associate anything with Him, establish the prescribed prayer, pay the obligatory Zakah, and fast Ramadān",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported: A Bedouin came to the Prophet (may Allah's peace and blessings be upon him) and said: Direct me to a deed that will make me enter Paradise if I do it. He said: \"Worship Allah and do not associate anything with Him, establish the prescribed prayer, pay the obligatory Zakah, and fast Ramadān.\" He said: By the One in Whose Hand my soul is, I will not do more than this. When he left, the Prophet (may Allah's peace and blessings be upon him) said: \"Whoever is pleased to look at a man from the dwellers of Paradise, let him look at this.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/3689",
    "sha256": "f3ff017718c6d331f946b87bf1ed5e55630ec246e3a59ce0b7c725350936969a",
    "charCount": 592
  },
  "4563": {
    "id": "4563",
    "title": "Islam is to testify that there is no god but Allah and that Muhammad is the Messenger of Allah, to establish prayer, to pay Zakah, to fast Ramadan, and to perform Hajj to the House if you are able to find a way thereto",
    "hadith_text": "‘Umar ibn al-Khattāb (may Allah be pleased with him) reported: One day, we were sitting with the Messenger of Allah (may Allah's peace and blessings be upon him) when there appeared before us a man dressed in extremely white clothes and had very black hair. No traces of travel were visible on him, and none of us knew him. He came in and sat down opposite the Prophet (may Allah's peace and blessings be upon him), rested his knees against his, and placed the palms of his hands on his (the Prophet's) thighs. He said: \"O Muhammad, tell me about Islam.\" The Messenger of Allah (may Allah's peace and blessings be upon him) said: \"Islam is to testify that there is no god but Allah and that Muhammad is the Messenger of Allah, to establish prayer, to pay Zakah, to fast Ramadan, and to perform Hajj to the House if you are able to find a way thereto.\" He said: \"You have spoken the truth.\" We wondered how he asked him and affirmed his truthfulness. Then, he said: \"Tell me about Imān (faith).\" He said: \"It is to believe in Allah, His angels, His books, His messengers, and the Last Day, and believe in the divine decree, the pleasant and unpleasant aspects thereof.\" Then, he said: \"You have spoken the truth.\" Then, he said: \"Tell me about ihsān.\" He said: \"It is to worship Allah as if you see Him, for if you do not see Him, He sees you.\" He said: \"Tell me about the Hour.\" He said: \"The one questioned about it knows no more than the questioner.\" He said: \"Then, tell me about its signs.\" He said: \"The slave girl will give birth to her mistress, and you will see the barefoot, naked, and destitute herdsmen competing in constructing lofty buildings.\" Then, he departed. I stayed for a while, and then he said to me: \"O 'Umar, do you know who the questioner was?\" I said: \"Allah and His Messenger know best.\" He said: \"He was Jibrīl (Gabriel). He came to teach you your religion.\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/4563",
    "sha256": "f0abe0a43f6a03cb1c557714216cbf0a482feebce284ea3f254219523b50e31c",
    "charCount": 1886
  },
  "4968": {
    "id": "4968",
    "title": "What if there was a river at the door of any of you wherein he takes a bath five times a day? Would there remain any of his filth?",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported that he heard the Messenger of Allah (may Allah's peace and blessings be upon him) say: \"What if there was a river at the door of any of you wherein he takes a bath five times a day? Would there remain any of his filth?\" They said: Nothing of his filth would remain. He said: \"This is similar to the five prayers by means of which Allah erases sins.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/4968",
    "sha256": "3ce42af3809e1d2170017f9d3932ac7bd51213dd8feda414733c2759fdc08d54",
    "charCount": 404
  },
  "5460": {
    "id": "5460",
    "title": "People will be gathered on the Day of Judgment barefooted, naked, and uncircumcised",
    "hadith_text": "‘Ā’ishah, the Mother of the Believers (may Allah be pleased with her) reported: I heard the Messenger of Allah (may Allah's peace and blessings be upon him) say: \"People will be gathered on the Day of Judgment barefooted, naked, and uncircumcised.\" I said: O Messenger of Allah, men and women together, looking at each other?! He replied: \"O ‘Ā’ishah, the situation will be too grave for them to be looking at each other.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/5460",
    "sha256": "4c7f7aa0693e504dbbe6f82309dd0c15d7d9d1c66a04fa30aa402938c1279baa",
    "charCount": 422
  },
  "5493": {
    "id": "5493",
    "title": "The strong believer is better and dearer to Allah than the weak believer, and there is good in both",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported that the Messenger of Allah (may Allah's peace and blessings be upon him) said: \"The strong believer is better and dearer to Allah than the weak believer, and there is good in both. Adhere to whatever brings you benefit, seek the help of Allah, and do not feel helpless. If something befalls you, do not say: 'Had I done such-and-such, it would have been such-and-such;' rather, say: 'Allah has decreed, and whatever He wills, He does.' Indeed, 'if' opens the way before the devil to act.\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/5493",
    "sha256": "a249a17d98eaccd187c1566608690c8519f1dfd9a30e729ed7b5f3d1d9b05a49",
    "charCount": 543
  },
  "5913": {
    "id": "5913",
    "title": "The best of you are those who learn the Qur’an and teach it",
    "hadith_text": "‘Uthmān ibn ‘Affān (may Allah be pleased with him) reported: The Prophet (may Allah’s peace and blessings be upon him) said: \"The best of you are those who learn the Qur’an and teach it.\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Al-Bukhāri]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/5913",
    "sha256": "698fbdc17c7be97dd7efd21fffae41cac1325c9136356edfb7cfbfd07b0a8cbf",
    "charCount": 187
  },
  "6078": {
    "id": "6078",
    "title": "What is the matter with those people who said such-and-such? But indeed, I pray and sleep, I fast and break the fast, and I marry women. Whoever turns away from my Sunnah does not belong to me",
    "hadith_text": "Anas (may Allah be pleased with him) reported: A group from among the Prophet's Companions asked the wives of the Prophet (may Allah's peace and blessings be upon him) about his deeds in private. Some of them said: I will not marry women. Others said: I will not eat meat. Some others said: I will not sleep on a bed. So, he praised Allah and commended Him and said: \"What is the matter with those people who said such-and-such? But indeed, I pray and sleep, I fast and break the fast, and I marry women. Whoever turns away from my Sunnah does not belong to me.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/6078",
    "sha256": "8cb1ac5ae45ec84fd3771e76595f8418fd1f927d04a19ef2851eb528692ece7d",
    "charCount": 562
  },
  "6383": {
    "id": "6383",
    "title": "Whoever obeys me has obeyed Allah, and whoever disobeys me has disobeyed Allah; and whoever obeys the leader has obeyed me, and whoever disobeys the leader has disobeyed me",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported that the Prophet (may Allah's peace and blessings be upon him) said: \"Whoever obeys me has obeyed Allah, and whoever disobeys me has disobeyed Allah; and whoever obeys the leader has obeyed me, and whoever disobeys the leader has disobeyed me.\"",
    "grade": "[Authentic hadith]",
    "takhrij": "[Narrated by Bukhari & Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/6383",
    "sha256": "77e448a101c38d03c481e9c8c3556e3e972e06a43ccfd3869e9c918a61b6f3db",
    "charCount": 298
  },
  "64673": {
    "id": "64673",
    "title": "Verily, Allah has ninety-nine names, one-hundred minus one. Whoever memorizes them all will enter Paradise",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported that the Messenger of Allah (may Allah's peace and blessings be upon him) said: \"Verily, Allah has ninety-nine names, one-hundred minus one. Whoever memorizes them all will enter Paradise.\"",
    "grade": "[Authentic hadith]",
    "takhrij": "[Narrated by Bukhari & Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/64673",
    "sha256": "8fddebc2783d825b8d6434e52c187f2564df65c99c41538e5b51ee49b22cbddf",
    "charCount": 243
  },
  "65000": {
    "id": "65000",
    "title": "Islam is built on five",
    "hadith_text": "‘Abdullah ibn ‘Umar (may Allah be pleased with him and his father) reported that the Messenger of Allah (may Allah's peace and blessings be upon him) said: \"Islam is built on five: testifying that there is no god but Allah and that Muhammad is His slave and Messenger, establishing prayer, giving Zakah, performing Hajj to the (Sacred) House, and fasting Ramadān.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/65000",
    "sha256": "0095a7e0820be67dbdd9e3206a1913d95eb2ddecfd96998a635bc745d7cb6a9c",
    "charCount": 364
  },
  "65003": {
    "id": "65003",
    "title": "Do you think that if I perform the obligatory payers, fast Ramadan, treat the lawful as lawful, and treat the unlawful as unlawful,",
    "hadith_text": "Jābir (may Allah be pleased with him) reported: A man said to the Messenger of Allah (may Allah's peace and blessings be upon him): \"Do you think that if I perform the obligatory payers, fast Ramadan, treat the lawful as lawful, and treat the unlawful as unlawful, and do not do anything else beyond that, will I enter Paradise?\" He said: 'Yes.' He said: \"By Allah, I will not do anything more than that.\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/65003",
    "sha256": "6fee64c862636b57aff7e33cd22e0d1242c256ab594133836042ef5f648a0eb3",
    "charCount": 405
  },
  "65007": {
    "id": "65007",
    "title": "Allah's right upon His servants is that they should worship Him and associate no partners with Him. And the right of the servants upon Allah is that He should not punish whoever associates no partners with Him",
    "hadith_text": "Mu‘ādh (may Allah be pleased with him) reported: I was riding behind the Prophet (may Allah’s peace and blessings be upon him) on a donkey called ‘Ufayr. The Prophet (may Allah’s peace and blessings be upon him) asked: \"O Mu‘ādh, do you know what Allah's right upon His servants is, and what the right of His servants upon Him is?\" I replied: \"Allah and His Messenger know best.\" He said: \"Allah's right upon His servants is that they should worship Him and associate no partners with Him. And the right of the servants upon Allah is that He should not punish whoever associates no partners with Him.\" I said: \"O Messenger of Allah, should I not inform the people of this good news?\" He said: \"Do not inform them of it, lest they depend on it solely.\"",
    "grade": "[Authentic]",
    "takhrij": "[Agreed upon]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/65007",
    "sha256": "bac4903c9922728d6b4c2e7662e52f061212a6d9d913ca90415421af73c4148f",
    "charCount": 751
  },
  "65038": {
    "id": "65038",
    "title": "Allah decreed the destinies of the creatures fifty thousand years before He created the heavens and the earth",
    "hadith_text": "‘Abdullāh ibn ‘Amr ibn al-‘Ās (may Allah be pleased with him) reported: I heard the Messenger of Allah (may Allah’s peace and blessings be upon him) say: \"Allah decreed the destinies of the creatures fifty thousand years before He created the heavens and the earth.\" He said: \"when His Throne was upon the water.”",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Muslim]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/65038",
    "sha256": "edebe2c9c34cd15b472b28216a14a8e42fb79ad17ec1ba865cd3a8b39f752c16",
    "charCount": 313
  },
  "65046": {
    "id": "65046",
    "title": "Neither believe nor disbelieve the People of the Book but say: {We believe in Allah and what has been sent down to us",
    "hadith_text": "Abu Hurayrah (may Allah be pleased with him) reported: The People of the Book used to read the Torah in Hebrew and expound on it in Arabic to the Muslims. So, the Messenger of Allah (may Allah’s peace and blessings be upon him) said: \"Neither believe nor disbelieve the People of the Book but say: {We believe in Allah and what has been sent down to us.} [Surat al-Baqarah: 136].\"",
    "grade": "[Authentic]",
    "takhrij": "[Narrated by Al-Bukhāri]",
    "lang": "en",
    "link": "https://hadeethenc.com/en/browse/hadith/65046",
    "sha256": "af87aabda2fe222aa06386d831a53658fc1cb48784dab02e6bfbc776495d7a3c",
    "charCount": 380
  }
});
