export const CONTENT_MANIFEST = {
  schemaVersion: 1,
  revision: "2026-08-06-phase-one",
  verseIdentity: {
    field: "verse_key",
    pattern: "^[1-9][0-9]{0,2}:[1-9][0-9]{0,2}$",
    example: "2:255",
  },
  edition: {
    id: "quran-foundation-mushaf-1",
    mushafId: 1,
    name: "Madani Mushaf",
    riwayah: "Hafs 'an Asim",
    language: "ar",
    author: "Quran Foundation content services",
    lineModel: "15 fixed page-line slots",
    pages: 604,
    source: "Quran Foundation Content API",
    sourceUrl: "https://api-docs.quran.foundation/",
    attribution: "Quran text and page metadata provided through Quran Foundation/Quran.com.",
    license: "Upstream content terms apply; Quran content is not relicensed by this application.",
  },
  resources: {
    arabic: {
      id: "uthmani-mushaf-1",
      author: "Quran Foundation content services",
      language: "ar",
      edition: "Uthmani text aligned to Mushaf ID 1",
      source: "Quran Foundation Content API",
      sourceUrl: "https://api-docs.quran.foundation/",
      attribution: "Quran text provided through Quran Foundation/Quran.com.",
      license: "Upstream content terms apply; this application does not relicense Quran content.",
    },
    tajweed: {
      id: "uthmani-tajweed-qcf-v4",
      author: "Quran Foundation content services",
      language: "ar",
      edition: "Uthmani Tajweed markup with QCF V4 page glyphs",
      source: "Quran Foundation Content API",
      sourceUrl: "https://api-docs.quran.foundation/",
      attribution: "Tajweed markup and QCF page glyphs provided through Quran Foundation/Quran.com.",
      license: "Upstream content and font terms apply.",
    },
    transliteration: {
      id: 57,
      author: "Quran Foundation transliteration resource",
      language: "en-Latn",
      edition: "Quran.com resource 57",
      source: "Quran Foundation Content API",
      sourceUrl: "https://api-docs.quran.foundation/",
      attribution: "Transliteration displayed from Quran.com resource 57.",
      license: "Upstream content terms apply.",
    },
    translation: {
      id: 20,
      author: "Saheeh International",
      language: "en",
      edition: "Quran.com resource 20",
      source: "Quran Foundation Content API",
      sourceUrl: "https://api-docs.quran.foundation/",
      attribution: "Saheeh International translation displayed from Quran.com resource 20.",
      license: "Upstream content terms apply; this application does not relicense the translation.",
    },
  },
  integrity: {
    algorithm: "SHA-256",
    scope: "Normalized page number, verse keys, Arabic text, line mapping, and optional learning layers",
    responseField: "provenance.pageChecksum",
    lastFullAudit: {
      date: "2026-08-06",
      pages: 604,
      verses: 6236,
      status: "passed",
      corpusChecksum: "113b56770df729d941b6e0349862ad5cdd8256a54339011eebe220c5f904c2bb",
      report: "repository:docs/content-audit.json",
    },
  },
} as const;

export type ContentManifest = typeof CONTENT_MANIFEST;
