import type { RiwayahId } from "./reading-registry.mjs";

export type ReciterScope = "ayah" | "surah";
export type ReciterGroup = "default" | "other";
export type ReciterRiwayah = RiwayahId;
export type ReciterStyle = "murattal" | "mujawwad" | "muallim";
export type ReciterProvider = "quran-foundation" | "everyayah" | "kalamalah" | "mp3quran";

export type ReciterId =
  | "alafasy"
  | "abdulbasit"
  | "aymen"
  | "minshawi-kids"
  | "muhammad-ayyub"
  | "abdul-rashid-sufi"
  | "saad"
  | "abdulbasit-mujawwad"
  | "abdullah-basfar"
  | "sudais"
  | "shatri"
  | "ajmi"
  | "ahmed-neana"
  | "akram-alaqmi"
  | "ali-jaber"
  | "ali-hajjaj-suesy"
  | "aziz-alili"
  | "fares-abbad"
  | "hani-rifai"
  | "hudhaify"
  | "husary"
  | "husary-muallim"
  | "husary-mujawwad"
  | "ibrahim-akhdar"
  | "juhany"
  | "karim-mansoori"
  | "khalifa-tunaiji"
  | "khalid-qahtani"
  | "maher-muaiqly"
  | "mahmoud-ali-banna"
  | "matroud"
  | "minshawi"
  | "minshawi-mujawwad"
  | "tablawi"
  | "muhammad-abdulkareem"
  | "muhammad-jibreel"
  | "muhsin-qasim"
  | "nabil-rifai"
  | "nasser-qatami"
  | "parhizgar"
  | "sahl-yassin"
  | "salah-bukhatir"
  | "salah-budair"
  | "saud-shuraym"
  | "yaser-salamah"
  | "yasser-dussary"
  | "akram-alalaqmi"
  | "mohammed-al-muhasny"
  | "mahmoud-khalil-al-hussary"
  | "idrees-abkr"
  | "mahmoud-ali-albanna"
  | "mishary-alafasi"
  | "mustafa-ismail"
  | "mustafa-al-lahoni"
  | "mustafa-raad-alazawy"
  | "muftah-alsaltany"
  | "alzain-mohammad-ahmad"
  | "abdulelah-bin-aoun"
  | "majed-al-zamil"
  | "maher-shakhashero"
  | "khalid-almohana"
  | "adel-al-khalbany"
  | "mousa-bilal"
  | "hatem-fareed-alwaer"
  | "ibrahim-aljormy"
  | "mahmood-al-rifai"
  | "tawfeeq-as-sayegh"
  | "ibrahim-aldosari"
  | "jamal-shaker-abdullah"
  | "jamaan-alosaimi"
  | "yousef-bin-noah-ahmad"
  | "moeedh-alharthi"
  | "mohammad-rashad-alshareef"
  | "khalid-al-jileel"
  | "ahmed-al-trabulsi"
  | "abdullah-alqarafi"
  | "abdulbadi-ghailan"
  | "muhammad-burhaji"
  | "yusuf-alaidroos"
  | "hassan-aldaghriri"
  | "muhammad-al-faqih"
  | "junaid-adam-abdullah"
  | "khalid-alziyadi"
  | "abdul-rahman-bin-abdul-razzaq-al-badr"
  | "alijon-qori"
  | "mohammed-al-zubaidi"
  | "asim-al-luhaidan"
  | "mahmoud-harfoush"
  | "bandar-balilah"
  | "wadeea-al-yamani"
  | "khalid-abdulkafi"
  | "raad-al-kurdi"
  | "abdulrahman-aloosi"
  | "mohammad-khalil-al-qari"
  | "rami-aldeais"
  | "abdulrahman-al-majed"
  | "abdullah-al-mousa"
  | "abdullah-al-khalaf"
  | "mansour-al-salemi"
  | "nasser-alosfor"
  | "dawood-hamza"
  | "mohammad-albukheet"
  | "nasser-almajed"
  | "ahmed-al-swailem"
  | "bader-alturki"
  | "ahmad-shaheen"
  | "saad-almqren"
  | "ahmad-al-nufais"
  | "omar-al-darweez"
  | "ahmad-deban"
  | "abdullah-kamel"
  | "peshawa-qadr-al-kurdi"
  | "nathier-almalki"
  | "haitham-aldukhain"
  | "mahmoud-abdul-hakam"
  | "ahmad-issa-al-maasaraawi"
  | "hashim-abu-dalal"
  | "fouad-alkhamery"
  | "sayed-ahmad-hashemi"
  | "khalid-mohammadi"
  | "mal-allah-abdulrhman-aljaber"
  | "salman-alsadeiq"
  | "hasan-saleh"
  | "abdulrahman-alshahhat"
  | "issa-omar-sanankoua"
  | "saleh-alquraishi"
  | "ibrahim-al-asiri"
  | "saleh-alshamrani"
  | "faisal-al-hajry"
  | "anas-alemadi"
  | "abdulkareem-alhazmi"
  | "zaki-daghistani"
  | "sayeed-ramadan"
  | "shirazad-taher"
  | "saber-abdulhakm"
  | "saleh-alsahood"
  | "saleh-al-habdan"
  | "salah-alhashim"
  | "mukhtar-al-haj"
  | "adel-ryyan"
  | "abdelbari-al-toubayti"
  | "abdulbari-mohammad"
  | "abdul-aziz-al-ahmad"
  | "abdulaziz-az-zahrani"
  | "abdullah-albuajan"
  | "ahmad-al-hawashi"
  | "abdullah-khayyat"
  | "abdullah-qaulan"
  | "abdulmohsin-al-obaikan"
  | "abdulhadi-kanakeri"
  | "abdulwadood-haneef"
  | "abdulwali-al-arkani"
  | "emad-hafez"
  | "abdulaziz-alturki"
  | "ahmad-saber"
  | "neamah-al-hassan"
  | "yasser-al-qurashi"
  | "yahya-hawwa"
  | "yousef-alshoaey"
  | "abdullah-abdal";

export interface ReciterDefinition {
  id: ReciterId;
  name: string;
  initials: string;
  group: ReciterGroup;
  scope: ReciterScope;
  riwayah: ReciterRiwayah;
  style: ReciterStyle;
  provider: ReciterProvider;
  audioPath: string;
  bitrate?: string;
  source: string;
  sourceUrl: string;
  license: string;
  aliases?: string[];
}

export const DEFAULT_RECITER_ID: ReciterId;
export const DEFAULT_RECITERS: readonly ReciterDefinition[];
export const OTHER_RECITERS: readonly ReciterDefinition[];
export const RECITERS: readonly ReciterDefinition[];
export const RECITER_IDS: ReadonlySet<string>;

export function getReciterById(id: string): ReciterDefinition;
export function searchReciters(query: string, list?: readonly ReciterDefinition[]): ReciterDefinition[];
